### ISSUE TITLE
Make the activity fit for standard resolutions.

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/across-and-down-activity#11]
These buttons are not fully visible with screen resolution 1360x669 pixels.
![image](https://user-images.githubusercontent.com/35092582/50578089-a899ad80-0e5a-11e9-9298-8251fc9776c4.png)

**Comment by Aniket21mathur** [comment]
@quozl please check it.Thanks!

**Comment by chimosky** [comment]
Checked on a 1366x768 resolution and issue doesn't persist, buttons are clearly visible.
